{
  imports = [
    ./oil.nix
    ./bufferline.nix
    ./which-key.nix
    ./blink-cmp.nix
    ./mini.nix
    ./treesitter.nix
    ./lazygit.nix
    ./octo.nix
    ./rustaceanvim.nix
    ./conform.nix
    ./gitblame.nix
    ./gitsigns.nix
    ./telescope.nix
    ./grug-far.nix
    ./kulala.nix
    ./haskell-tools.nix
  ];
}
